src/objects/Dev_Answer_Obj__c.object
<CustomObject>
    <description>回答者が問題に対して回答した内容を管理するオブジェクトです。
このオブジェクトは連結オブジェクトです。
プレフィックス「AN」</description>
    <fields>
        <fullName>Dev_AN_Answer__c</fullName>
        <description>問題に対してどの回答を行ったかを入力する項目です。</description>
        <label>回答</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_AN_CorrectAnswer__c</fullName>
        <description>回答した問題の正答を入力する項目です。</description>
        <label>正答</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_AN_ExaminationHistory__c</fullName>
        <description>この回答を行った試験履歴を参照します。</description>
        <label>試験履歴</label>
        <referenceTo>Dev_ExamHistory_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_EH_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_Respondant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>この回答を行った回答者を選択します。</description>
        <label>回答者</label>
        <referenceTo>Dev_Respondant_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_RE_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_AN_TargetQuestion__c</fullName>
        <description>回答の対象問題を選択する項目です。</description>
        <label>問題</label>
        <referenceTo>Dev_Question_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_QU_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>回答</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>回答No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_Question_Obj__c.object
<CustomObject>
    <description>出題する問題を管理するオブジェクトです。
プレフィックス「QU」</description>
    <fields>
        <fullName>Dev_QU_Answer1__c</fullName>
        <description>問題に対する選択肢の1つです。
この項目は必須です。</description>
        <label>選択肢1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer2__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer3__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer4__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer5__c</fullName>
        <description>問題に対する解答を入力します。</description>
        <label>選択肢5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer6__c</fullName>
        <description>問題に対する解答を入力します。</description>
        <label>選択肢6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_CorrectAnswer__c</fullName>
        <description>解答に対して、正解を指定します。
入力は必須です。</description>
        <inlineHelpText>正解は選択肢の番号を入力してください。
（複数選択の場合は、カンマ区切りで昇順で入れてください。）</inlineHelpText>
        <label>正解</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Question__c</fullName>
        <description>問題出題の際の問題文を入力します。
255文字以内になるように調節してください。</description>
        <label>問題文</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>問題</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>問題No</label>
        <type>AutoNumber</type>
    </nameField>
    <recordTypes>
        <fullName>Dev_SingleAnswer_RecType</fullName>
        <active>true</active>
        <description>正解がひとつだけの問題を管理するレコードタイプです。</description>
        <label>単一正答</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dev_Dto_ExaminationAnswer.cls
public class Dev_Dto_ExaminationAnswer {

	/** 問題レコードタイプ「単一選択」 */
	private static String DEV_NAME_SINGLE_ANSWER = 'Dev_SingleAnswer_RecType';

	/** 問題レコードID */
	public Id questionId {get; set;}

	/** 問題文 */
	public String questionSentence {get; set;}

	/** 選択肢リスト */
	public List<SelectOption> options {get; set;}

	/** 回答者レコードID */
	public Id respondantId {get; set;}

	/** 正答No */
	public String correctAnswer {get; set;}

	/** 回答No */
	public String answer {get; set;}

    /** 単一選択問題識別フラグ */
    public Boolean isSingle {get; set;}

	/** コンストラクタ */
	public Dev_Dto_ExaminationAnswer( Dev_Question_Obj__c quData, Id respondantId ) {
		convertFromQuestion(quData, respondantId);
	}

	public void convertFromQuestion( Dev_Question_Obj__c quData, Id respondantId ){
		questionId = quData.Id;
		questionSentence = quData.Dev_QU_Question__c.replace('\n', '<br />');
		setOptions( quData );
		this.respondantId = respondantId;
		correctAnswer = quData.Dev_QU_CorrectAnswer__c;
		isSingle = quData.RecordType.DeveloperName == DEV_NAME_SINGLE_ANSWER;
	}

	private void setOptions( Dev_Question_Obj__c quData ){

		System.debug(quData);

        List<SelectOption> optionsTemp = new List<SelectOption>();
        optionsTemp.add(new SelectOption('1', (quData.Dev_QU_Answer1__c == null ? '' : quData.Dev_QU_Answer1__c)));
        optionsTemp.add(new SelectOption('2', (quData.Dev_QU_Answer2__c == null ? '' : quData.Dev_QU_Answer2__c)));
        optionsTemp.add(new SelectOption('3', (quData.Dev_QU_Answer3__c == null ? '' : quData.Dev_QU_Answer3__c)));
        optionsTemp.add(new SelectOption('4', (quData.Dev_QU_Answer4__c == null ? '' : quData.Dev_QU_Answer4__c)));

        if(quData.Dev_QU_Answer5__c != null){
	        optionsTemp.add(new SelectOption('5', quData.Dev_QU_Answer5__c));
        }

        if(quData.Dev_QU_Answer6__c != null){
	        optionsTemp.add(new SelectOption('6', quData.Dev_QU_Answer6__c));
        }

        options = new List<SelectOption>();

        while(!optionsTemp.isEmpty()){
            Integer size = optionsTemp.size();
            Integer randomNo = Math.floor(Math.random() * size).intValue();
            options.add(optionsTemp.remove(randomNo));
        }

	}

	public Dev_Answer_Obj__c convertToAnswer(Id examHistoryId){

		Dev_Answer_Obj__c anData = new Dev_Answer_Obj__c();
		anData.Dev_AN_TargetQuestion__c = questionId;
		anData.Dev_AN_Respondant__c = respondantId;
		anData.Dev_AN_CorrectAnswer__c = correctAnswer;
		anData.Dev_AN_Answer__c = answer;
		anData.Dev_AN_ExaminationHistory__c = examHistoryId;
		return anData;

	}

	public void setAnswerFromMultiSelect(String[] multiSelect){

		Integer[] multiSelectNum = new Integer[]{};

		for(String numStr : multiSelect){
			multiSelectNum.add(Integer.valueOf(numStr));
		}

		multiSelectNum.sort();

		answer = String.join(multiSelectNum, ';');
	}

	public String[] getAnswerToMultiSelect(){
		if(answer == null){
			return new String[]{};
		}else {
			return answer.split(';');
		}
	}

}