src/objects/Dev_Answer_Obj__c.object
<CustomObject>
    <description>回答者が問題に対して回答した内容を管理するオブジェクトです。
このオブジェクトは連結オブジェクトです。
プレフィックス「AN」</description>
    <fields>
        <fullName>Dev_AN_ExaminationHistory__c</fullName>
        <description>この回答を行った試験履歴を参照します。</description>
        <label>試験履歴</label>
        <referenceTo>Dev_ExamHistory_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_EH_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_TargetQuestion__c</fullName>
        <description>回答の対象問題を選択する項目です。</description>
        <label>問題</label>
        <referenceTo>Dev_Question_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_QU_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_isCorrect__c</fullName>
        <description>実際の回答と、正解が一致している場合は「○」を
一致していない場合は「✕」を出力します。</description>
        <formula>if(  Dev_AN_CorrectAnswer__c  = Dev_AN_Answer__c , &quot;○&quot;, &quot;×&quot; )</formula>
        <label>正誤</label>
        <type>Text</type>
    </fields>
    <label>回答</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>回答No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_ExamHistory_Obj__c.object
<CustomObject>
    <description>試験の結果、合格判定などの履歴を保持します。
プレフィックス「EH」</description>
    <fields>
        <fullName>Dev_EH_BorderLine__c</fullName>
        <label>合格ライン</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EH_CorrectAnswerNum__c</fullName>
        <label>正解数</label>
        <summaryFilterItems>
            <field>Dev_Answer_Obj__c.Dev_AN_isCorrect__c</field>
            <operation>equals</operation>
            <value>○</value>
        </summaryFilterItems>
        <summaryForeignKey>Dev_Answer_Obj__c.Dev_AN_ExaminationHistory__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamQuestionNum__c</fullName>
        <label>試験問題数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamResult__c</fullName>
        <formula>if( Dev_EH_BorderLine__c &lt;=  Dev_EH_CorrectAnswerNum__c , &apos;合格&apos;, &apos;不合格&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>試験結果</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamTrialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>試験実施者</label>
        <referenceTo>Dev_Respondant_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_RE_ExaminationHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_EH_TrialExam__c</fullName>
        <label>実施試験</label>
        <referenceTo>Dev_ExaminationMaster_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_EM_ExaminationHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>試験履歴</label>
    <nameField>
        <displayFormat>EH-{YYYY}{MM}{dd}-{000}</displayFormat>
        <label>試験履歴No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_ExaminationMaster_Obj__c.object
<CustomObject>
    <description>試験の情報を管理するオブジェクトです。
プレフィックス「EM」</description>
    <label>試験マスタ</label>
    <nameField>
        <label>試験マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dev_Question_Obj__c.object
<CustomObject>
    <description>出題する問題を管理するオブジェクトです。
プレフィックス「QU」</description>
    <label>問題</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>問題No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_Respondant_Obj__c.object
<CustomObject>
    <description>問題演習の回答者を管理するオブジェクトです。
プレフィックス「RE」</description>
    <fields>
        <fullName>Dev_RE_MailAddress__c</fullName>
        <label>メールアドレス</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>回答者</label>
    <nameField>
        <label>回答者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dev_Dao_ExaminationHistory_Obj.cls
public with sharing class Dev_Dao_ExaminationHistory_Obj {

    private static Dev_Dao_ExaminationHistory_Obj dao;

    private Dev_Dao_ExaminationHistory_Obj(){}

    public static Dev_Dao_ExaminationHistory_Obj getInstance(){
        if(dao == null){
            return new Dev_Dao_ExaminationHistory_Obj();
        }else{
            return dao;
        }
    }

    public Dev_ExamHistory_Obj__c getExaminationHistoryById(Id ehId){

        List<Dev_ExamHistory_Obj__c> targetEhList =
                [
                    SELECT
                        Id,
                        Dev_EH_TrialExam__r.Name,
                        Dev_EH_ExamTrialist__r.Name,
                        Dev_EH_ExamTrialist__r.Dev_RE_MailAddress__c,
                        Dev_EH_ExamResult__c,
                        Dev_EH_ExamQuestionNum__c,
                        Dev_EH_CorrectAnswerNum__c,
                        Dev_EH_BorderLine__c,
                        (
                            SELECT
                                Dev_AN_TargetQuestion__r.Dev_QU_Question__c,
                                Dev_AN_isCorrect__c
                            FROM
                                Dev_EH_Answers__r
                        )
                    FROM
                        Dev_ExamHistory_Obj__c
                    WHERE
                        Id = :ehId
                ];

        return targetEhList.get(0);

    }
}