src/objects/Dev_Answer_Obj__c.object
<CustomObject>
    <description>回答者が問題に対して回答した内容を管理するオブジェクトです。
このオブジェクトは連結オブジェクトです。
プレフィックス「AN」</description>
    <fields>
        <fullName>Dev_AN_Respondant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>この回答を行った回答者を選択します。</description>
        <label>回答者</label>
        <referenceTo>Dev_Respondant_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_RE_Answers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_AN_TargetQuestion__c</fullName>
        <description>回答の対象問題を選択する項目です。</description>
        <label>問題</label>
        <referenceTo>Dev_Question_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_QU_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_isCorrect__c</fullName>
        <description>実際の回答と、正解が一致している場合は「○」を
一致していない場合は「✕」を出力します。</description>
        <formula>if(  Dev_AN_CorrectAnswer__c  = Dev_AN_Answer__c , &quot;○&quot;, &quot;×&quot; )</formula>
        <label>正誤</label>
        <type>Text</type>
    </fields>
    <label>回答</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>回答No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dev_Dao_Answer_Obj.cls
public with sharing class Dev_Dao_Answer_Obj {

    private static Dev_Dao_Answer_Obj dao;

    private Dev_Dao_Answer_Obj(){}

    public static Dev_Dao_Answer_Obj getInstance(){
        if(dao == null){
            return new Dev_Dao_Answer_Obj();
        }else{
            return dao;
        }
    }

    public List<Dev_Answer_Obj__c> getAnswerByQuestionIdsAndRespondant(Set<Id> questionIdSet, Id respondantId){
        return [
                SELECT
                	Dev_AN_isCorrect__c
                FROM
                    Dev_Answer_Obj__c
                WHERE
                	Dev_AN_respondant__c = :respondantId
                	AND
                	Dev_AN_targetQuestion__c IN :questionIdSet
                ORDER BY
                	Dev_AN_targetQuestion__c, createdDate
                ];
    }

}