src/objects/Dev_ExaminationMaster_Obj__c.object
<CustomObject>
    <description>試験の情報を管理するオブジェクトです。
プレフィックス「EM」</description>
    <fields>
        <fullName>Dev_EM_RegisteredQuestionSum__c</fullName>
        <label>問題数</label>
        <summaryForeignKey>Dev_Question_Obj__c.Dev_QU_ExaminationMaster__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>試験マスタ</label>
    <nameField>
        <label>試験マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dev_Respondant_Obj__c.object
<CustomObject>
    <description>問題演習の回答者を管理するオブジェクトです。
プレフィックス「RE」</description>
    <label>回答者</label>
    <nameField>
        <label>回答者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dev_CL_ExaminationSetting.cls
public class Dev_CL_ExaminationSetting{
    
    /** 出題問題数 */
    public String examMaster {get; set;}
    
    /** 回答者 */
    public String respondant {get; set;}
    
    public Dev_CL_ExaminationSetting(){}

    public List<SelectOption> getExamMasterList(){
        List<SelectOption> examMasterList = new List<SelectOption>();
        for(Dev_ExaminationMaster_Obj__c emData : [SELECT Id, Name FROM Dev_ExaminationMaster_Obj__c where Dev_EM_RegisteredQuestionSum__c > 0]){
            examMasterList.add(new SelectOption(emData.Id, emData.Name));
        }
        return examMasterList;
    }

    public List<SelectOption> getRespondantList(){
        List<SelectOption> respondantList = new List<SelectOption>();
        respondantList.add(new SelectOption('0', '--なし--'));
        for(Dev_Respondant_Obj__c reData : [SELECT Id, Name FROM Dev_Respondant_Obj__c]){
            respondantList.add(new SelectOption(reData.Id, reData.Name));
        }
        return respondantList;
    }

    public PageReference start(){

        if(respondant == '0'){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, '回答者を選択してください。'));
            return null;
        }

        PageReference nextPage = Page.Dev_VF_Examination;

        nextPage.getParameters().put('examMaster', examMaster);
        nextPage.getParameters().put('respondant', respondant);

        return nextPage;
    }
}