src/objects/Dev_Answer_Obj__c.object
<CustomObject>
    <description>回答者が問題に対して回答した内容を管理するオブジェクトです。
このオブジェクトは連結オブジェクトです。
プレフィックス「AN」</description>
    <fields>
        <fullName>Dev_AN_ExaminationHistory__c</fullName>
        <description>この回答を行った試験履歴を参照します。</description>
        <label>試験履歴</label>
        <referenceTo>Dev_ExamHistory_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_EH_Answers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_TargetQuestion__c</fullName>
        <description>回答の対象問題を選択する項目です。</description>
        <label>問題</label>
        <referenceTo>Dev_Question_Obj__c</referenceTo>
        <relationshipLabel>回答</relationshipLabel>
        <relationshipName>Dev_QU_Answers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Dev_AN_isCorrect__c</fullName>
        <description>実際の回答と、正解が一致している場合は「○」を
一致していない場合は「✕」を出力します。</description>
        <formula>if(  Dev_AN_CorrectAnswer__c  = Dev_AN_Answer__c , &quot;○&quot;, &quot;×&quot; )</formula>
        <label>正誤</label>
        <type>Text</type>
    </fields>
    <label>回答</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>回答No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_CheckAnswerMail_Obj__c.object
<CustomObject>
    <description>回答内容をメールで送信する際の情報を管理するオブジェクトです。
プレフィックス「CA」</description>
    <fields>
        <fullName>Dev_CA_Contents__c</fullName>
        <label>内容</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Dev_CA_Reciever__c</fullName>
        <label>宛先</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Dev_CA_Subject__c</fullName>
        <label>タイトル</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>回答内容確認メール</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>回答内容確認メールNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dev_ExamHistory_Obj__c.object
<CustomObject>
    <description>試験の結果、合格判定などの履歴を保持します。
プレフィックス「EH」</description>
    <fields>
        <fullName>Dev_EH_CorrectAnswerNum__c</fullName>
        <label>正解数</label>
        <summaryFilterItems>
            <field>Dev_Answer_Obj__c.Dev_AN_isCorrect__c</field>
            <operation>equals</operation>
            <value>○</value>
        </summaryFilterItems>
        <summaryForeignKey>Dev_Answer_Obj__c.Dev_AN_ExaminationHistory__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamQuestionNum__c</fullName>
        <label>試験問題数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamResult__c</fullName>
        <formula>if( Dev_EH_BorderLine__c &lt;=  Dev_EH_CorrectAnswerNum__c , &apos;合格&apos;, &apos;不合格&apos; )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>試験結果</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamTrialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>試験実施者</label>
        <referenceTo>Dev_Respondant_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_RE_ExaminationHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_EH_TrialExam__c</fullName>
        <label>実施試験</label>
        <referenceTo>Dev_ExaminationMaster_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_EM_ExaminationHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>試験履歴</label>
    <nameField>
        <displayFormat>EH-{YYYY}{MM}{dd}-{000}</displayFormat>
        <label>試験履歴No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_ExaminationMaster_Obj__c.object
<CustomObject>
    <description>試験の情報を管理するオブジェクトです。
プレフィックス「EM」</description>
    <label>試験マスタ</label>
    <nameField>
        <label>試験マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dev_Question_Obj__c.object
<CustomObject>
    <description>出題する問題を管理するオブジェクトです。
プレフィックス「QU」</description>
    <fields>
        <fullName>Dev_QU_Question__c</fullName>
        <description>問題出題の際の問題文を入力します。
255文字以内になるように調節してください。</description>
        <label>問題文</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>問題</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>問題No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_Respondant_Obj__c.object
<CustomObject>
    <description>問題演習の回答者を管理するオブジェクトです。
プレフィックス「RE」</description>
    <fields>
        <fullName>Dev_RE_MailAddress__c</fullName>
        <label>メールアドレス</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>回答者</label>
    <nameField>
        <label>回答者名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dev_CL_ShowResult.cls
public with sharing class Dev_CL_ShowResult {

	public Dev_ExamHistory_Obj__c result {get; set;}

	public String email {get; set;}

	public Boolean sendOnlyIncorrect {get; set;}

	public Dev_CL_ShowResult() {}

	public void init(){
        Id ehId = ApexPages.currentPage().getParameters().get('examinationHistory');
        Dev_Dao_ExaminationHistory_Obj ehDao = Dev_Dao_ExaminationHistory_Obj.getInstance();
        result = ehDao.getExaminationHistoryById(ehId);
        email = result.Dev_EH_ExamTrialist__r.Dev_RE_MailAddress__c;
	}

	public PageReference createEmail(){
		createCaData();
		return new PageReference('/home/home.jsp');
	}

	public PageReference gotoHome(){
		createCaData();
		return new PageReference('/home/home.jsp');
	}

	private void createCaData(){
		System.debug('create CaData start');
		Dev_CheckAnswerMail_Obj__c caData = new Dev_CheckAnswerMail_Obj__c();
		caData.Dev_CA_Reciever__c = email;
		caData.Dev_CA_Subject__c = '試験結果：'+ result.Dev_EH_TrialExam__r.Name + DateTime.now().format('yyyyMMdd');
		caData.Dev_CA_Contents__c = '';

		caData.Dev_CA_Contents__c += '試験名： ' + result.Dev_EH_TrialExam__r.Name + '\n';
		caData.Dev_CA_Contents__c += '正解数： ' + result.Dev_EH_CorrectAnswerNum__c + ' / ' + result.Dev_EH_ExamQuestionNum__c + '\n';
		caData.Dev_CA_Contents__c += '試験結果： ' + result.Dev_EH_ExamResult__c + '\n\n';
		caData.Dev_CA_Contents__c += '回答詳細： ' +  + '\n';

		Integer questionNo = 1;

		for(Dev_Answer_Obj__c anData : result.Dev_EH_Answers__r){

			if(sendOnlyIncorrect && anData.Dev_AN_isCorrect__c == '○'){
				continue;
			}

			caData.Dev_CA_Contents__c += '試験No.' + questionNo + '\n';
			caData.Dev_CA_Contents__c += '問題文: ' + anData.Dev_AN_TargetQuestion__r.Dev_QU_Question__c + '\n';
			caData.Dev_CA_Contents__c += '正誤: ' + anData.Dev_AN_isCorrect__c + '\n';
			caData.Dev_CA_Contents__c += 'URL: https://ap2.salesforce.com/' + anData.Id + '\n\n';
			questionNo++;

		}

		insert caData;
		System.debug('create CaData end');

	}

}