src/objects/Dev_ExaminationMaster_Obj__c.object
<CustomObject>
    <description>試験の情報を管理するオブジェクトです。
プレフィックス「EM」</description>
    <fields>
        <fullName>Dev_EM_BorderLine__c</fullName>
        <description>試験合格に必要な正解数を入力する項目です。</description>
        <label>合格ライン(%)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dev_EM_ExamTime__c</fullName>
        <description>試験時間を入力します。
分単位で入力してください。</description>
        <label>試験時間（分）</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EM_QuestionNo__c</fullName>
        <description>試験の出題数を入力する項目です。</description>
        <label>出題数</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>試験マスタ</label>
    <nameField>
        <label>試験マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dev_Dao_ExaminationMaster_Obj.cls
public class Dev_Dao_ExaminationMaster_Obj {

    private static Dev_Dao_ExaminationMaster_Obj dao;
    
    private Dev_Dao_ExaminationMaster_Obj(){}

    public static Dev_Dao_ExaminationMaster_Obj getInstance(){
        if(dao == null){
            return new Dev_Dao_ExaminationMaster_Obj();
        }else{
            return dao;
        }
    }
    
    public Dev_ExaminationMaster_Obj__c getExaminationMasterById(Id emId){

        List<Dev_ExaminationMaster_Obj__c> targetEmList =
            [
                SELECT
                    Id,
                    Dev_EM_QuestionNo__c,
                    Dev_EM_ExamTime__c,
                    Dev_EM_BorderLine__c
                FROM
                    Dev_ExaminationMaster_Obj__c
                WHERE
                	Id = :emId
            ];

        return targetEmList.get(0);

    }
}