src/objects/Dev_Question_Obj__c.object
<CustomObject>
    <description>出題する問題を管理するオブジェクトです。
プレフィックス「QU」</description>
    <fields>
        <fullName>Dev_QU_Answer1__c</fullName>
        <description>問題に対する選択肢の1つです。
この項目は必須です。</description>
        <label>選択肢1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer2__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer3__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer4__c</fullName>
        <description>問題に対する解答を入力します。
入力は必須です。</description>
        <label>選択肢4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer5__c</fullName>
        <description>問題に対する解答を入力します。</description>
        <label>選択肢5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Answer6__c</fullName>
        <description>問題に対する解答を入力します。</description>
        <label>選択肢6</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_CorrectAnswer__c</fullName>
        <description>解答に対して、正解を指定します。
入力は必須です。</description>
        <inlineHelpText>正解は選択肢の番号を入力してください。
（複数選択の場合は、カンマ区切りで昇順で入れてください。）</inlineHelpText>
        <label>正解</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dev_QU_ExaminationMaster__c</fullName>
        <description>問題の属する試験マスタを選択します。</description>
        <label>試験マスタ</label>
        <referenceTo>Dev_ExaminationMaster_Obj__c</referenceTo>
        <relationshipLabel>問題</relationshipLabel>
        <relationshipName>Dev_EM_Questions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dev_QU_Question__c</fullName>
        <description>問題出題の際の問題文を入力します。
255文字以内になるように調節してください。</description>
        <label>問題文</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>問題</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>問題No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dev_Dao_Question_Obj.cls
public class Dev_Dao_Question_Obj{

    private static Dev_Dao_Question_Obj dao;
    
    private Dev_Dao_Question_Obj(){}

    public static Dev_Dao_Question_Obj getInstance(){
        if(dao == null){
            return new Dev_Dao_Question_Obj();
        }else{
            return dao;
        }
    }
    
    public List<Dev_Question_Obj__c> getQuestionByAnyNumberAndExaminationMaster(Integer questionNo, Id emId){

        List<Dev_Question_Obj__c> allQuestionList =
            [
                SELECT
                    Id,
                    Dev_QU_Question__c,
                    Dev_QU_Answer1__c,
                    Dev_QU_Answer2__c,
                    Dev_QU_Answer3__c,
                    Dev_QU_Answer4__c,
                    Dev_QU_Answer5__c,
                    Dev_QU_Answer6__c,
                    Dev_QU_CorrectAnswer__c,
                    RecordType.DeveloperName
                FROM
                    Dev_Question_Obj__c
                WHERE
                    Dev_QU_ExaminationMaster__c = :emId
            ];

        Set<Integer> randomNumSet = new Set<Integer>();

        if(questionNo > allQuestionList.size()){
            questionNo = allQuestionList.size();
        }

        while(randomNumSet.size() != questionNo){
            Integer num = (Math.random() * allQuestionList.size()).intValue();
            randomNumSet.add(num);
        }

        List<Dev_Question_Obj__c> targetQuestionList = new List<Dev_Question_Obj__c>();

        for(Integer targetNum : randomNumSet){
            targetQuestionList.add(allQuestionList.get(targetNum));
        }

        return targetQuestionList;

    }

}