src/objects/Dev_Answer_Obj__c.object
<CustomObject>
    <description>回答者が問題に対して回答した内容を管理するオブジェクトです。
このオブジェクトは連結オブジェクトです。
プレフィックス「AN」</description>
    <label>回答</label>
    <nameField>
        <displayFormat>AN-{00000}</displayFormat>
        <label>回答No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_ExamHistory_Obj__c.object
<CustomObject>
    <description>試験の結果、合格判定などの履歴を保持します。
プレフィックス「EH」</description>
    <fields>
        <fullName>Dev_EH_BorderLine__c</fullName>
        <label>合格ライン</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamQuestionNum__c</fullName>
        <label>試験問題数</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EH_ExamTrialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>試験実施者</label>
        <referenceTo>Dev_Respondant_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_RE_ExaminationHistories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dev_EH_TrialExam__c</fullName>
        <label>実施試験</label>
        <referenceTo>Dev_ExaminationMaster_Obj__c</referenceTo>
        <relationshipLabel>試験履歴</relationshipLabel>
        <relationshipName>Dev_EM_ExaminationHistories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>試験履歴</label>
    <nameField>
        <displayFormat>EH-{YYYY}{MM}{dd}-{000}</displayFormat>
        <label>試験履歴No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dev_ExaminationMaster_Obj__c.object
<CustomObject>
    <description>試験の情報を管理するオブジェクトです。
プレフィックス「EM」</description>
    <fields>
        <fullName>Dev_EM_BorderLine__c</fullName>
        <description>試験合格に必要な正解数を入力する項目です。</description>
        <label>合格ライン(%)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Dev_EM_ExamTime__c</fullName>
        <description>試験時間を入力します。
分単位で入力してください。</description>
        <label>試験時間（分）</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dev_EM_QuestionNo__c</fullName>
        <description>試験の出題数を入力する項目です。</description>
        <label>出題数</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>試験マスタ</label>
    <nameField>
        <label>試験マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Dev_Question_Obj__c.object
<CustomObject>
    <description>出題する問題を管理するオブジェクトです。
プレフィックス「QU」</description>
    <label>問題</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>問題No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Dev_Dto_Examination.cls
public with sharing class Dev_Dto_Examination {

	/** 問題・回答リスト */
	private List<Dev_Dto_ExaminationAnswer> examAnsList
		= new List<Dev_Dto_ExaminationAnswer>();

	/** 試験マスタID */
	public Id emId {get; set;}

	/** 回答者ID */
    public Id respondantId {get; set;}

	/** 試験時間 */
	public Integer timer {get; set;}

	/** 出題数 */
	public Integer questionNum {get; set;}

	private Integer borderLine {get; set;}

	public Dev_Dto_Examination() {}

	public void init() {

        setExamMaster();

	}

    private void setExamMaster(){
        Dev_Dao_ExaminationMaster_Obj emDao = Dev_Dao_ExaminationMaster_Obj.getInstance();
        emId = ApexPages.currentPage().getParameters().get('examMaster');

	    // 選択した試験マスタ取得
	    Dev_ExaminationMaster_Obj__c emData = emDao.getExaminationMasterById(emId);
        timer = (emData.Dev_EM_ExamTime__c * 60).intValue();

        setQuestion(emData.Dev_EM_QuestionNo__c.intValue());
        questionNum = examAnsList.size();
        borderLine = Math.ceil((questionNum * (emData.Dev_EM_BorderLine__c / 100))).intValue();
    }

    private void setQuestion(Integer questionNum){

        // 問題のDaoのインスタンスを取得
        Dev_Dao_Question_Obj quDao = Dev_Dao_Question_Obj.getInstance();

        List<Dev_Question_Obj__c> questionList = new List<Dev_Question_Obj__c>();

        // 設定画面で設定した試験マスタをもとに問題を取得します。
        questionList = quDao.getQuestionByAnyNumberAndExaminationMaster(questionNum, emId);

        respondantId = ApexPages.currentPage().getParameters().get('respondant');

        for(Integer i = 0; i < questionList.size(); i++){
            setExam(new Dev_Dto_ExaminationAnswer(questionList.get(i), respondantId));
        }

    }

    public Id submit(){

    	Dev_ExamHistory_Obj__c ehData = createEhData();
    	insert ehData;

        List<Dev_Answer_Obj__c> anList = new List<Dev_Answer_Obj__c>();

        for(Dev_Dto_ExaminationAnswer examAns : examAnsList){
            anList.add(examAns.convertToAnswer(ehData.Id));
        }

        insert anList;

        return ehData.Id;
    }

    private Dev_ExamHistory_Obj__c createEhData(){
    	Dev_ExamHistory_Obj__c ehData = new Dev_ExamHistory_Obj__c();
   		ehData.Dev_EH_TrialExam__c = emId;
   		ehData.Dev_EH_ExamTrialist__c = respondantId;
		ehData.Dev_EH_BorderLine__c = borderLine;
		ehData.Dev_EH_ExamQuestionNum__c = questionNum;
   		return ehData;
    }

    public Dev_Dto_ExaminationAnswer getExam(Integer index){
		if(index >= examAnsList.size()){
			return null;
		} else {
			return examAnsList.get(index);
		}
	}

	public void setExam(Dev_Dto_ExaminationAnswer examAns){
		examAnsList.add(examAns);
	}

	public Integer getExamSize(){
		if(examAnsList == null){
			return 0;
		}else{
			return examAnsList.size();
		}
	}

}