src/objects/Dev_CheckAnswerMail_Obj__c.object
<CustomObject>
    <description>回答内容をメールで送信する際の情報を管理するオブジェクトです。
プレフィックス「CA」</description>
    <fields>
        <fullName>Dev_CA_SendMeilFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>メール送信済フラグ</label>
        <type>Checkbox</type>
    </fields>
    <label>回答内容確認メール</label>
    <nameField>
        <displayFormat>CA-{00000}</displayFormat>
        <label>回答内容確認メールNo</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Dev_BT_DeleteCaData.cls
global class Dev_BT_DeleteCaData implements Database.Batchable<sObject> {

	private Integer totalDeleteData;

	global Dev_BT_DeleteCaData() {
		totalDeleteData = 0;
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(
			[
				SELECT
					id
				FROM
					Dev_CheckAnswerMail_Obj__c
				WHERE
					Dev_CA_SendMeilFlag__c = true
			]
		);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {

   		delete scope;
   		totalDeleteData += scope.size();

	}

	global void finish(Database.BatchableContext BC) {

	}

}